// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://topmniglebzmcyxjnfll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvcG1uaWdsZWJ6bWN5eGpuZmxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MjQwOTYsImV4cCI6MjA3MDMwMDA5Nn0.k-xWg_pqBSqd4XrjjV9o_tN5aIamA8deM9n3PhkcOhk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});